apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-service
spec:
  name: service.vm.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: ExternalService
metadata:
  name: external-service
spec:
  hosts:
    - service.vm.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  discovery: STATIC
  endpoints:
  - address: 172.17.0.13
    ports:
      http: 80
    labels:
      version: v1
  - address: 172.17.0.13
    ports:
      http: 80
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-service
spec:
  hosts:
  - service.vm.svc.cluster.local
  http:
  - route:
    - destination:
        name: service.vm.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        name: service.vm.svc.cluster.local
        subset: v2
      weight: 50