apiVersion: v1
kind: Service
metadata:
  name: test-server-v2
  labels:
    app: test-server
    version: v2
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: http-health
    port: 81
  selector:
    app: test-server
